# Generated by Django 5.2.12 on 2026-04-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operador'), ('director', 'Diretor')], default='operator', max_length=20, verbose_name='perfil'),
        ),
    ]
