# Generated by Django 4.2.29 on 2026-04-05 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status_sipac', models.CharField(max_length=255)),
                ('situacao_requisicao', models.CharField(blank=True, max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('origem', models.CharField(choices=[('importacao', 'Importação'), ('manual', 'Manual')], default='manual', max_length=20)),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='ImportacaoArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('tipo_arquivo', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluida', 'Concluída'), ('falha', 'Falha')], default='pendente', max_length=20)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('resumo_json', models.JSONField(blank=True, default=dict)),
                ('mensagem_erro', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('chave_normalizada', models.CharField(editable=False, max_length=255, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('visivel_publicamente', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='RegraPrioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('chave_normalizada', models.CharField(max_length=255, unique=True)),
                ('prioridade', models.CharField(choices=[('1 - Urgente', '1 - Urgente'), ('2 - Alta', '2 - Alta'), ('3 - Média', '3 - Média'), ('4 - Baixa', '4 - Baixa'), ('5 - Analisar', '5 - Analisar'), ('6 - Inativa', '6 - Inativa')], max_length=30)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('origem', models.CharField(default='planilha', max_length=50)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('prioridade', 'chave_normalizada'),
            },
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('ano', models.PositiveIntegerField(blank=True, null=True)),
                ('assunto', models.TextField(blank=True)),
                ('data_cadastro', models.DateField(blank=True, null=True)),
                ('tipo_requisicao', models.CharField(blank=True, max_length=255)),
                ('divisao', models.CharField(blank=True, max_length=255)),
                ('unidade_origem', models.CharField(blank=True, max_length=255)),
                ('status_sipac', models.CharField(blank=True, max_length=255)),
                ('situacao_requisicao', models.CharField(blank=True, max_length=20)),
                ('tipo_servico', models.CharField(blank=True, max_length=255)),
                ('servico', models.CharField(blank=True, max_length=255)),
                ('local_servico', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('dias_desde_abertura', models.IntegerField(blank=True, null=True)),
                ('nome_requisitante_snapshot', models.CharField(blank=True, max_length=255)),
                ('unidade_setor_snapshot', models.CharField(blank=True, max_length=255)),
                ('contato_direto_url', models.URLField(blank=True, max_length=1000)),
                ('situacao_texto', models.TextField(blank=True)),
                ('status_fluxo', models.CharField(blank=True, max_length=50)),
                ('gravidade', models.CharField(blank=True, max_length=100)),
                ('urgencia', models.CharField(blank=True, max_length=100)),
                ('tendencia', models.CharField(blank=True, max_length=100)),
                ('gut_score', models.PositiveIntegerField(default=0)),
                ('gut_nivel', models.CharField(blank=True, max_length=20)),
                ('sinfra_responsavel', models.CharField(blank=True, max_length=100)),
                ('prioridade_final', models.CharField(blank=True, choices=[('1 - Urgente', '1 - Urgente'), ('2 - Alta', '2 - Alta'), ('3 - Média', '3 - Média'), ('4 - Baixa', '4 - Baixa'), ('5 - Analisar', '5 - Analisar'), ('6 - Inativa', '6 - Inativa')], max_length=30)),
                ('link_atendimento', models.URLField(blank=True, max_length=1000)),
                ('link_sipac', models.URLField(blank=True, max_length=1000)),
                ('data_execucao', models.DateField(blank=True, null=True)),
                ('dias_para_execucao', models.IntegerField(blank=True, null=True)),
                ('visivel_publicamente', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-ano', '-numero'),
            },
        ),
        migrations.CreateModel(
            name='Requisitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('chave_normalizada', models.CharField(editable=False, max_length=255)),
                ('unidade_setor', models.CharField(blank=True, max_length=255)),
                ('contato_url', models.URLField(blank=True, max_length=1000)),
                ('visivel_publicamente', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='TaxonomiaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('divisao', models.CharField(max_length=255)),
                ('tipo_servico', models.CharField(max_length=255)),
                ('servico', models.CharField(blank=True, max_length=255)),
                ('chave_normalizada', models.CharField(editable=False, max_length=255, unique=True)),
                ('ordem_divisao', models.PositiveIntegerField(blank=True, null=True)),
                ('ordem_tipo', models.PositiveIntegerField(blank=True, null=True)),
                ('ordem_servico', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('divisao', 'tipo_servico', 'servico'),
            },
        ),
        migrations.AddConstraint(
            model_name='requisitante',
            constraint=models.UniqueConstraint(fields=('chave_normalizada', 'unidade_setor'), name='tracker_unique_requisitante'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='importacao_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes', to='tracker.importacaoarquivo'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='predio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes', to='tracker.predio'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='requisitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes', to='tracker.requisitante'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='taxonomia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes', to='tracker.taxonomiaservico'),
        ),
        migrations.AddField(
            model_name='importacaoarquivo',
            name='iniciado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacoes_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicostatus',
            name='requisicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='tracker.requisicao'),
        ),
        migrations.AddField(
            model_name='historicostatus',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_registrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
