# Generated by Django 5.2.12 on 2026-04-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='orcamento',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
