# Generated by Django 5.2.12 on 2026-04-05 23:59

import unicodedata

from django.db import migrations, models


def backfill_status_sipac_options(apps, schema_editor):
    Requisicao = apps.get_model("tracker", "Requisicao")
    StatusSipacOpcao = apps.get_model("tracker", "StatusSipacOpcao")

    seen = {}
    for status in Requisicao.objects.exclude(status_sipac="").values_list("status_sipac", flat=True).order_by("status_sipac").distinct():
        descricao = " ".join((status or "").replace("\xa0", " ").split())
        if not descricao:
            continue
        ordem = seen.setdefault(descricao, len(seen) + 1)
        chave_normalizada = unicodedata.normalize("NFKD", descricao)
        chave_normalizada = "".join(char for char in chave_normalizada if not unicodedata.combining(char))
        chave_normalizada = "".join(chave_normalizada.lower().split())
        StatusSipacOpcao.objects.update_or_create(
            descricao=descricao,
            defaults={
                "chave_normalizada": chave_normalizada,
                "ordem": ordem,
                "ativa": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_requisicao_orcamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusSipacOpcao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("descricao", models.CharField(max_length=255, unique=True)),
                ("chave_normalizada", models.CharField(editable=False, max_length=255, unique=True)),
                ("ordem", models.PositiveIntegerField(blank=True, null=True)),
                ("ativa", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("ordem", "descricao"),
            },
        ),
        migrations.AlterField(
            model_name="requisicao",
            name="contato_direto_url",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="requisitante",
            name="contato_url",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.RunPython(backfill_status_sipac_options, migrations.RunPython.noop),
    ]
