# Generated by Django 5.2.12 on 2026-04-06 00:15

import unicodedata

from django.db import migrations


def backfill_status_sipac_options(apps, schema_editor):
    Requisicao = apps.get_model("tracker", "Requisicao")
    StatusSipacOpcao = apps.get_model("tracker", "StatusSipacOpcao")

    seen = {}
    for status in Requisicao.objects.exclude(status_sipac="").values_list("status_sipac", flat=True).order_by("status_sipac").distinct():
        descricao = " ".join((status or "").replace("\xa0", " ").split())
        if not descricao:
            continue
        ordem = seen.setdefault(descricao, len(seen) + 1)
        chave_normalizada = unicodedata.normalize("NFKD", descricao)
        chave_normalizada = "".join(char for char in chave_normalizada if not unicodedata.combining(char))
        chave_normalizada = "".join(chave_normalizada.lower().split())
        StatusSipacOpcao.objects.update_or_create(
            descricao=descricao,
            defaults={
                "chave_normalizada": chave_normalizada,
                "ordem": ordem,
                "ativa": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_statussipacopcao_and_phone_fields"),
    ]

    operations = [
        migrations.RunPython(backfill_status_sipac_options, migrations.RunPython.noop),
    ]
