# Generated by Django 5.2.12 on 2026-04-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_backfill_status_sipac_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requisicao",
            name="dias_desde_abertura",
        ),
    ]
