# Generated by Django 5.2.12 on 2026-04-05 00:00

import unicodedata

from django.db import migrations, models


STATUS_SIPAC_FLOW = (
    ("01", "Cadastrada", "01 CADASTRADA"),
    ("02", "Enviada", "02 ENVIADA"),
    ("03", "Aguardando OS", "03 AGUARDANDO OS"),
    ("04", "OS emitida", "04 OS EMITIDA"),
    ("05", "Aguardando avaliação requisitante", "05 AGUARDANDO AVALIAÇÃO REQUISITANTE"),
    ("06", "Finalizada", "06 FINALIZADA"),
    ("07", "Retornada", "07 RETORNADA"),
    ("08", "Estornada", "08 ESTORNADA"),
    ("09", "Negada", "09 NEGADA"),
    ("10", "Pendente de autorização chefe unidade", "10 PENDENTE DE AUTORIZAÇÃO CHEFE UNIDADE"),
    ("11", "Não executado - motivo diverso", "11 NÃO EXECUTADO - MOTIVO DIVERSO"),
    ("12", "Não executado - abrir processo", "12 NÃO EXECUTADO - ABRIR PROCESSO"),
    ("12", "Não executado - abrir processo (Em análise)", "12 NÃO EXECUTADO - ABRIR PROCESSO (Em análise)"),
    ("13", "Não executado - finalizada pelo tempo SINFRA", "13 NÃO EXECUTADO - FINALIZADA PELO TEMPO SINFRA"),
    ("14", "Não executado - reabrir requisição", "14 NÃO EXECUTADO - REABRIR REQUISIÇÃO"),
    ("15", "Não executado - finalizada falta de resposta", "15 NÃO EXECUTADO - FINALIZADA FALTA DE RESPOSTA"),
    ("16", "Não executado - setor de projetos", "16 NÃO EXECUTADO - SETOR DE PROJETOS"),
)


def normalize_key(value: str) -> str:
    text = unicodedata.normalize("NFKD", value or "")
    text = "".join(char for char in text if not unicodedata.combining(char))
    return "".join(text.lower().split())


def seed_status_flow(apps, schema_editor):
    StatusSipacOpcao = apps.get_model("tracker", "StatusSipacOpcao")

    canonical_keys = set()
    for ordem, (numero, rotulo, descricao) in enumerate(STATUS_SIPAC_FLOW, start=1):
        chave = normalize_key(descricao)
        canonical_keys.add(chave)
        StatusSipacOpcao.objects.update_or_create(
            chave_normalizada=chave,
            defaults={
                "numero": numero,
                "rotulo": rotulo,
                "descricao": descricao,
                "ordem": ordem,
                "ativa": True,
            },
        )

    ordem_extra = len(STATUS_SIPAC_FLOW)
    for item in StatusSipacOpcao.objects.exclude(chave_normalizada__in=canonical_keys).order_by("descricao"):
        ordem_extra += 1
        item.numero = item.numero or ""
        item.rotulo = item.rotulo or item.descricao or ""
        item.ordem = item.ordem or ordem_extra
        item.save(update_fields=["numero", "rotulo", "ordem"])


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_remove_requisicao_dias_desde_abertura"),
    ]

    operations = [
        migrations.AddField(
            model_name="statussipacopcao",
            name="numero",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="statussipacopcao",
            name="rotulo",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(seed_status_flow, migrations.RunPython.noop),
    ]
