# Generated by Django 5.2.12 on 2026-04-08 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_statussipacopcao_flow_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcompanhamentoRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('atualizacao_situacao', models.TextField()),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to='tracker.requisicao')),
            ],
            options={
                'verbose_name': 'Acompanhamento da requisição',
                'verbose_name_plural': 'Acompanhamentos da requisição',
                'ordering': ('data', 'criado_em', 'pk'),
            },
        ),
    ]
