# Generated by Django 5.2.12 on 2026-04-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_recalculate_execution_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statussipacopcao',
            options={'ordering': ('ordem', 'numero', 'descricao')},
        ),
        migrations.AddField(
            model_name='requisicao',
            name='observacao_diretor',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='status_processo_diretor',
            field=models.CharField(choices=[('nao_indicado', 'Não Indicado'), ('aguardando_decisao', 'Aguardando Decisão'), ('autorizado', 'Autorizado'), ('negado', 'Negado')], default='nao_indicado', max_length=20),
        ),
    ]
