# Generated by Django 5.2.12 on 2026-04-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_statussipacopcao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='empresa',
            field=models.CharField(blank=True, max_length=255, verbose_name='Empresa'),
        ),
    ]
