# Generated by Django 5.2.12 on 2026-04-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_requisicao_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='GUTParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('GRAVIDADE', 'Gravidade'), ('URGENCIA', 'Urgência'), ('TENDENCIA', 'Tendência')], max_length=20)),
                ('valor', models.PositiveSmallIntegerField()),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Parâmetro GUT',
                'verbose_name_plural': 'Parâmetros GUT',
                'ordering': ('tipo', '-valor'),
                'unique_together': {('tipo', 'valor')},
            },
        ),
    ]
