# Generated by Django 5.2.12 on 2026-04-10 00:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_reforcoempenho_numero_processo_sipac'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncaminhamentoDiretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(editable=False, unique=True)),
                ('data_encaminhamento', models.DateField(default=datetime.date.today)),
                ('tipo', models.CharField(choices=[('abrir_processo', 'Abrir processo'), ('encerrar_requisicao', 'Encerrar requisicao')], max_length=30)),
                ('orientacoes', models.TextField(verbose_name='Orientacoes do diretor')),
                ('diretor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encaminhamentos_diretor', to=settings.AUTH_USER_MODEL)),
                ('requisicoes', models.ManyToManyField(blank=True, related_name='encaminhamentos_diretor', to='tracker.requisicao', verbose_name='Requisicoes')),
            ],
            options={
                'verbose_name': 'Encaminhamento do diretor',
                'verbose_name_plural': 'Encaminhamentos do diretor',
                'ordering': ('-numero', '-data_encaminhamento', '-criado_em'),
            },
        ),
    ]
