# Generated by Django 5.2.12 on 2026-04-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_encaminhamentodiretor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encaminhamentodiretor',
            name='tipo',
            field=models.CharField(choices=[('abrir_processo', 'Abrir processo'), ('encerrar_requisicao', 'Encerrar requisicao'), ('inspecionar_in_loco', 'Inspecionar in loco')], max_length=30),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='status_processo_diretor',
            field=models.CharField(choices=[('nao_indicado', 'Não Indicado'), ('aguardando_decisao', 'Aguardando Decisão'), ('autorizado', 'Autorizado'), ('negado', 'Negado'), ('inspecao_in_loco', 'Inspecionar in loco')], default='nao_indicado', max_length=20),
        ),
    ]
