# Generated by Django 5.2.12 on 2026-04-10 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0018_alter_encaminhamentodiretor_tipo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="acompanhamentorequisicao",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acompanhamentos_registrados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
