# Generated by Django 5.2.12 on 2026-04-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_acompanhamentorequisicao_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encaminhamentodiretor',
            name='requisicoes',
            field=models.ManyToManyField(blank=True, related_name='encaminhamentos_diretor', to='tracker.requisicao', verbose_name='Requisições'),
        ),
        migrations.AlterField(
            model_name='encaminhamentodiretor',
            name='tipo',
            field=models.CharField(choices=[('abrir_processo', 'Abrir processo'), ('encerrar_requisicao', 'Encerrar requisição'), ('inspecionar_in_loco', 'Inspecionar in loco')], max_length=30),
        ),
    ]
