# Generated by Django 5.2.12 on 2026-04-30 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_meta_and_timestamped_fields'),
        ('tracker', '0026_e0_requisicao_fk_renames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='empenho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_empenho', to='core.empenho', verbose_name='Empenho'),
        ),
    ]
