# Generated by Django 5.2.12 on 2026-04-30 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_alter_meta_and_timestamped_fields'),
        ('tracker', '0027_alter_requisicao_empenho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero_sequencial', models.PositiveSmallIntegerField(default=1, help_text='1º, 2º, 3º orçamento do processo', verbose_name='Número sequencial')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor (R$)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de emissão')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de validade')),
                ('arquivo_planilha', models.FileField(blank=True, upload_to='processos/orcamentos/', verbose_name='Arquivo/planilha')),
                ('historico_negociacao', models.TextField(blank=True, verbose_name='Histórico de negociação')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'db_table': 'processos_orcamento',
                'ordering': ['processo', 'numero_sequencial'],
            },
        ),
        migrations.CreateModel(
            name='OrcamentoEmpenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('valor_alocado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor alocado (R$)')),
                ('data_vinculacao', models.DateField(blank=True, null=True, verbose_name='Data de vinculação')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('empenho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento_empenhos', to='core.empenho', verbose_name='Empenho')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento_empenhos', to='processos.orcamento', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Vínculo Orçamento-Empenho',
                'verbose_name_plural': 'Vínculos Orçamento-Empenho',
                'db_table': 'processos_orcamentoempenho',
                'unique_together': {('orcamento', 'empenho')},
            },
        ),
        migrations.AddField(
            model_name='orcamento',
            name='empenhos',
            field=models.ManyToManyField(blank=True, related_name='orcamentos', through='processos.OrcamentoEmpenho', to='core.empenho', verbose_name='Empenhos'),
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero_processo', models.CharField(max_length=50, unique=True, verbose_name='Número do processo')),
                ('data_abertura', models.DateField(blank=True, null=True, verbose_name='Data de abertura')),
                ('data_os', models.DateField(blank=True, null=True, verbose_name='Data da OS')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de conclusão')),
                ('data_arquivamento', models.DateField(blank=True, null=True, verbose_name='Data de arquivamento')),
                ('assunto', models.TextField(blank=True, verbose_name='Assunto')),
                ('classificacao_az', models.CharField(blank=True, help_text='Letra de ordenação para priorização A–Z', max_length=1, verbose_name='Classificação A-Z')),
                ('link_sipac', models.URLField(blank=True, verbose_name='Link SIPAC')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('acompanhamento_ct', models.TextField(blank=True, help_text='Histórico de acompanhamento interno do CT', verbose_name='Acompanhamento CT')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='core.empresa', verbose_name='Empresa')),
                ('encaminhamento_diretor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='tracker.encaminhamentodiretor', verbose_name='Encaminhamento ao diretor')),
                ('gerencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='core.gerenciasinfra', verbose_name='Gerência SINFRA')),
                ('predio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='core.predio', verbose_name='Prédio')),
                ('requisicoes', models.ManyToManyField(blank=True, related_name='processos', to='tracker.requisicao', verbose_name='Requisições vinculadas')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='core.servicoprocesso', verbose_name='Serviço')),
                ('situacao_sipac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='core.situacaosipac', verbose_name='Situação SIPAC')),
                ('solicitantes', models.ManyToManyField(blank=True, related_name='processos', to='core.solicitante', verbose_name='Solicitantes')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='core.statusprocesso', verbose_name='Status')),
                ('tipo_ambiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='core.tipoambiente', verbose_name='Tipo de ambiente')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'db_table': 'processos_processo',
                'ordering': ['-data_abertura', 'numero_processo'],
            },
        ),
        migrations.AddField(
            model_name='orcamento',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='processos.processo', verbose_name='Processo'),
        ),
    ]
