# Generated by Codex on 2026-05-01

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='unidade_origem',
            field=models.CharField(blank=True, max_length=255, verbose_name='Unidade de origem'),
        ),
        migrations.CreateModel(
            name='InteressadoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(blank=True, max_length=100, verbose_name='Tipo')),
                ('identificador', models.CharField(blank=True, max_length=80, verbose_name='Identificador')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interessados', to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Interessado do processo',
                'verbose_name_plural': 'Interessados do processo',
                'db_table': 'processos_interessadoprocesso',
                'ordering': ['processo', 'tipo', 'nome'],
                'unique_together': {('processo', 'tipo', 'identificador', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='AcompanhamentoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(verbose_name='Data')),
                ('atualizacao', models.TextField(verbose_name='Atualização da situação')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to='processos.processo', verbose_name='Processo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acompanhamentos_processo', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Acompanhamento do processo',
                'verbose_name_plural': 'Acompanhamentos do processo',
                'db_table': 'processos_acompanhamentoprocesso',
                'ordering': ('data', 'criado_em', 'pk'),
            },
        ),
    ]
