# Generated by Django 5.2.12 on 2026-05-01 15:23

import datetime
from django.db import migrations


def migrar_acompanhamento_ct(apps, schema_editor):
    """
    Converte o campo de texto livre `acompanhamento_ct` (e `observacao`, se houver)
    em registros estruturados de AcompanhamentoProcesso.

    Cada processo com `acompanhamento_ct` não-vazio recebe um registro com:
      - data = data_abertura do processo (fallback: 2024-01-01)
      - atualizacao = texto original do campo
    """
    Processo = apps.get_model('processos', 'Processo')
    AcompanhamentoProcesso = apps.get_model('processos', 'AcompanhamentoProcesso')
    data_fallback = datetime.date(2024, 1, 1)

    for proc in Processo.objects.exclude(acompanhamento_ct='').filter(acompanhamento_ct__isnull=False):
        data = proc.data_abertura or data_fallback
        AcompanhamentoProcesso.objects.create(
            processo=proc,
            data=data,
            atualizacao=proc.acompanhamento_ct.strip(),
        )


def reverter(apps, schema_editor):
    """Remove os registros criados pela migração (sem restaurar o campo original)."""
    # Não é possível reverter de forma segura sem saber quais foram criados aqui,
    # então apenas limpa todos os acompanhamentos sem usuário e com data = data_abertura.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_unidade_origem_interessado'),
    ]

    operations = [
        migrations.RunPython(migrar_acompanhamento_ct, reverter),
    ]
