# Generated by Django 5.2.12 on 2026-05-01 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_migrar_acompanhamento_ct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(blank=True, help_text='Ex: 1.0, 2.0', max_length=20, verbose_name='Número')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor (R$)')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='processos.orcamento', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Item de Orçamento',
                'verbose_name_plural': 'Itens de Orçamento',
                'db_table': 'processos_item_orcamento',
                'ordering': ['ordem', 'numero'],
            },
        ),
    ]
