# Generated by Django 5.2.12 on 2026-05-01 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0004_add_item_orcamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('rotulo', models.CharField(blank=True, help_text='Ex: Desconto, BDI, ISS', max_length=100, verbose_name='Rótulo')),
                ('percentual', models.DecimalField(decimal_places=4, help_text='Negativo para desconto (ex: -18.5), positivo para acréscimo (ex: 25.0)', max_digits=8, verbose_name='Percentual (%)')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='processos.orcamento', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Ajuste de Orçamento',
                'verbose_name_plural': 'Ajustes de Orçamento',
                'db_table': 'processos_ajuste_orcamento',
                'ordering': ['ordem'],
            },
        ),
    ]
