# Generated by Django 5.2.12 on 2026-04-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fix_timestamped_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divisaosinfra',
            options={'ordering': ('nome',), 'verbose_name': 'Divisão SINFRA', 'verbose_name_plural': 'Divisões SINFRA'},
        ),
        migrations.AlterModelOptions(
            name='movimentacaoempenho',
            options={'ordering': ('-criado_em',), 'verbose_name': 'Movimentação de Empenho', 'verbose_name_plural': 'Movimentações de Empenho'},
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ('tipo_servico__divisao__nome', 'tipo_servico__nome', 'nome'), 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterModelOptions(
            name='statusrequisicao',
            options={'ordering': ('ordem', 'numero', 'codigo'), 'verbose_name': 'Status de requisição', 'verbose_name_plural': 'Status de requisições'},
        ),
        migrations.AlterModelOptions(
            name='tiposervico',
            options={'ordering': ('divisao__nome', 'nome'), 'verbose_name': 'Tipo de serviço', 'verbose_name_plural': 'Tipos de serviço'},
        ),
        migrations.AlterField(
            model_name='gerenciasinfra',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicoprocesso',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='situacaosipac',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='statusprocesso',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
